### ISSUE TITLE
Please add support install using proxy

### ISSUE THREAD

**Issue by patsevanton** [kostiantyn-nemchenko/ansible-role-patroni#32]
Please add support install using proxy

**Comment by kostiantyn-nemchenko** [comment]
Hi!
Could you be more specific, please?
What kind of proxy do you mean? HAProxy?

**Comment by patsevanton** [comment]
HI!
Install patroni using this playbook using squid in Corporate NetWork.

**Comment by kostiantyn-nemchenko** [comment]
This role has to install Patroni and its dependencies to make the daemon up and running.
Rest components related to Postgres HA cluster should be installed separately by other Ansible roles. Otherwise, this project will quickly become unmaintainable with lots of dependencies, bugs and feature requests to implement one more dependency.
